# Generated by Django 5.1.6 on 2025-04-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_customuser_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre_completo',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='numero_documento',
            field=models.CharField(default='Sin documento', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('avance_tratamiento', models.TextField()),
                ('medicamentos', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
