# Generated by Django 5.1.6 on 2025-04-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_alter_customuser_nombre_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='medicamentos',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='duracion_tratamiento',
            field=models.CharField(default='No especificado', max_length=100),
            preserve_default=False,
        ),
    ]
