# Generated by Django 5.1.6 on 2025-04-03 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_remove_historiaclinica_medicamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
