# Generated by Django 5.1.6 on 2025-04-04 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_historiaclinica_creado_en'),
    ]

    operations = [
    ]
