# Generated by Django 5.1.5 on 2025-04-12 22:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_llenar_numeros_historia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='avance_tratamiento',
            new_name='tratamiento',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='fecha',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EvolucionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('avance_tratamiento', models.TextField()),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='login_app.historiaclinica')),
            ],
        ),
    ]
